//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CourseOutcomesWCF.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CurriculumEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CurriculumEntities object using the connection string found in the 'CurriculumEntities' section of the application configuration file.
        /// </summary>
        public CurriculumEntities() : base("name=CurriculumEntities", "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CurriculumEntities object.
        /// </summary>
        public CurriculumEntities(string connectionString) : base(connectionString, "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CurriculumEntities object.
        /// </summary>
        public CurriculumEntities(EntityConnection connection) : base(connection, "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseOutcome> CourseOutcomes
        {
            get
            {
                if ((_CourseOutcomes == null))
                {
                    _CourseOutcomes = base.CreateObjectSet<CourseOutcome>("CourseOutcomes");
                }
                return _CourseOutcomes;
            }
        }
        private ObjectSet<CourseOutcome> _CourseOutcomes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseOutcomes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseOutcomes(CourseOutcome courseOutcome)
        {
            base.AddObject("CourseOutcomes", courseOutcome);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="courseSubject">No Metadata Documentation available.</param>
        /// <param name="courseNumber">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> usp_SELECT_CourseOutcomes(global::System.String courseSubject, global::System.String courseNumber)
        {
            ObjectParameter courseSubjectParameter;
            if (courseSubject != null)
            {
                courseSubjectParameter = new ObjectParameter("CourseSubject", courseSubject);
            }
            else
            {
                courseSubjectParameter = new ObjectParameter("CourseSubject", typeof(global::System.String));
            }
    
            ObjectParameter courseNumberParameter;
            if (courseNumber != null)
            {
                courseNumberParameter = new ObjectParameter("CourseNumber", courseNumber);
            }
            else
            {
                courseNumberParameter = new ObjectParameter("CourseNumber", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<global::System.String>("usp_SELECT_CourseOutcomes", courseSubjectParameter, courseNumberParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CurriculumModel", Name="CourseOutcome")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseOutcome : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseOutcome object.
        /// </summary>
        /// <param name="outcomesID">Initial value of the OutcomesID property.</param>
        public static CourseOutcome CreateCourseOutcome(global::System.Int32 outcomesID)
        {
            CourseOutcome courseOutcome = new CourseOutcome();
            courseOutcome.OutcomesID = outcomesID;
            return courseOutcome;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseSubject
        {
            get
            {
                return _CourseSubject;
            }
            set
            {
                OnCourseSubjectChanging(value);
                ReportPropertyChanging("CourseSubject");
                _CourseSubject = StructuralObject.SetValidValue(value, true, "CourseSubject");
                ReportPropertyChanged("CourseSubject");
                OnCourseSubjectChanged();
            }
        }
        private global::System.String _CourseSubject;
        partial void OnCourseSubjectChanging(global::System.String value);
        partial void OnCourseSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Catalog
        {
            get
            {
                return _Catalog;
            }
            set
            {
                OnCatalogChanging(value);
                ReportPropertyChanging("Catalog");
                _Catalog = StructuralObject.SetValidValue(value, true, "Catalog");
                ReportPropertyChanged("Catalog");
                OnCatalogChanged();
            }
        }
        private global::System.String _Catalog;
        partial void OnCatalogChanging(global::System.String value);
        partial void OnCatalogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseOutcomes
        {
            get
            {
                return _CourseOutcomes;
            }
            set
            {
                OnCourseOutcomesChanging(value);
                ReportPropertyChanging("CourseOutcomes");
                _CourseOutcomes = StructuralObject.SetValidValue(value, true, "CourseOutcomes");
                ReportPropertyChanged("CourseOutcomes");
                OnCourseOutcomesChanged();
            }
        }
        private global::System.String _CourseOutcomes;
        partial void OnCourseOutcomesChanging(global::System.String value);
        partial void OnCourseOutcomesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OutcomesID
        {
            get
            {
                return _OutcomesID;
            }
            set
            {
                if (_OutcomesID != value)
                {
                    OnOutcomesIDChanging(value);
                    ReportPropertyChanging("OutcomesID");
                    _OutcomesID = StructuralObject.SetValidValue(value, "OutcomesID");
                    ReportPropertyChanged("OutcomesID");
                    OnOutcomesIDChanged();
                }
            }
        }
        private global::System.Int32 _OutcomesID;
        partial void OnOutcomesIDChanging(global::System.Int32 value);
        partial void OnOutcomesIDChanged();

        #endregion

    }

    #endregion

}
