//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CourseOutcomesWCF.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CurriculumEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CurriculumEntities object using the connection string found in the 'CurriculumEntities' section of the application configuration file.
        /// </summary>
        public CurriculumEntities() : base("name=CurriculumEntities", "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CurriculumEntities object.
        /// </summary>
        public CurriculumEntities(string connectionString) : base(connectionString, "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CurriculumEntities object.
        /// </summary>
        public CurriculumEntities(EntityConnection connection) : base(connection, "CurriculumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LearningOutcome> LearningOutcomes
        {
            get
            {
                if ((_LearningOutcomes == null))
                {
                    _LearningOutcomes = base.CreateObjectSet<LearningOutcome>("LearningOutcomes");
                }
                return _LearningOutcomes;
            }
        }
        private ObjectSet<LearningOutcome> _LearningOutcomes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LearningOutcomes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLearningOutcomes(LearningOutcome learningOutcome)
        {
            base.AddObject("LearningOutcomes", learningOutcome);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="courseID">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> usp_SELECT_LearningOutcomes(global::System.String courseID)
        {
            ObjectParameter courseIDParameter;
            if (courseID != null)
            {
                courseIDParameter = new ObjectParameter("CourseID", courseID);
            }
            else
            {
                courseIDParameter = new ObjectParameter("CourseID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<global::System.String>("usp_SELECT_LearningOutcomes", courseIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CurriculumModel", Name="LearningOutcome")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LearningOutcome : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LearningOutcome object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static LearningOutcome CreateLearningOutcome(global::System.String courseID)
        {
            LearningOutcome learningOutcome = new LearningOutcome();
            learningOutcome.CourseID = courseID;
            return learningOutcome;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false, "CourseID");
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LearningOutcome1
        {
            get
            {
                return _LearningOutcome1;
            }
            set
            {
                OnLearningOutcome1Changing(value);
                ReportPropertyChanging("LearningOutcome1");
                _LearningOutcome1 = StructuralObject.SetValidValue(value, true, "LearningOutcome1");
                ReportPropertyChanged("LearningOutcome1");
                OnLearningOutcome1Changed();
            }
        }
        private global::System.String _LearningOutcome1;
        partial void OnLearningOutcome1Changing(global::System.String value);
        partial void OnLearningOutcome1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    #endregion

}
